# Generated by Django 5.1.1 on 2024-10-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='product',
        ),
        migrations.AddField(
            model_name='wallet',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, related_name='wallet', to='products.product', verbose_name='محصول'),
        ),
    ]
