# Generated by Django 5.1.1 on 2024-11-12 14:11

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', django_ckeditor_5.fields.CKEditor5Field()),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_keyboard', models.CharField(max_length=100, verbose_name='کلمه کلیدی')),
                ('text', django_ckeditor_5.fields.CKEditor5Field(verbose_name='متن')),
                ('featured_image', models.ImageField(upload_to='featured_images', verbose_name='تصویر شاخص')),
                ('seo_title', models.CharField(max_length=100, verbose_name='عنوان سئو')),
                ('meta_description', models.TextField(verbose_name='توضیحات متا')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('create_updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True, verbose_name='آدرس')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
                ('category', models.ManyToManyField(related_name='blog', to='blog.categoryblog', verbose_name='دسته یندی')),
            ],
            options={
                'verbose_name_plural': 'مقالات',
            },
        ),
    ]
