# Generated by Django 5.1.1 on 2024-10-14 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='نام کالا')),
                ('text', models.TextField(verbose_name='توضحات کالا')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('count', models.IntegerField(verbose_name='تعداد')),
                ('status', models.BooleanField(default=True, verbose_name='موجددی در انبار')),
                ('image', models.ImageField(upload_to='products/', verbose_name='عکس')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True, verbose_name='آدرس دهی')),
            ],
            options={
                'verbose_name_plural': 'محصولات',
            },
        ),
    ]
