# Generated by Django 5.1.1 on 2024-10-17 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='دسته بندی')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ManyToManyField(related_name='category', to='products.product', verbose_name='محصولات')),
            ],
        ),
    ]
